### ISSUE TITLE
Issues with Social login feature

### ISSUE THREAD

**Issue by dirkam** [baasbox/baasbox#499] opened 2014-10-06 09:05 UTC
If a user logs in with G+ and the server is restarted (or the session token gets expired) the user has to login again but can't access any of the resources.

BaasBox returns Success message for the login but if I try to access any resource I get permission error. E.g when I try to fetch the user info:

class com.baasbox.android.BaasClientException :{"result":"error","message":"User xxxxx is not authorized to access","resource":"/me","method":"GET","request_header":{"X-BAASBOX-APPCODE":["1234567890"],"Connection":["Keep-Alive"],"X-BB-SESSION":[“xxxxx"],"Accept-Encoding":["gzip"],"User-Agent":["BaasBox AndroidSDK/0.8.3a"],"Host":[“xxxxx"]},"API_version":"0.9.0-snapshot-nightly","http_code":401}
            at com.baasbox.android.NetworkTask.onClientError(NetworkTask.java:99)
            at com.baasbox.android.NetworkTask.parseResponse(NetworkTask.java:64)
            at com.baasbox.android.NetworkTask.asyncCall(NetworkTask.java:152)
            at com.baasbox.android.impl.Task.execute(Task.java:189)
            at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:170)

Tests:
- Logged in with FB, all good.
- Restarted the server itself where BaasBox is hosted.
- Session got expired and I could log in again with FB. Everything was fine.

Tried with G+ login and I get the not authorized response from BaasBox.
It seems that FB works fine, only G+ login is affected. Tried it with BaasBox user and it’s ok as well.

I noticed that if a BaasBox user is logged in and the server is restarted then the session token is still valid after the restart. This is great, can you make the social login to survive a server upgrade/restart, too? On mobile devices users don’t want to login every time the backend has been modified. Since it works with users created on BaasBox I hope there is a way to implement it with social login users.

Thanks

**Comment by erayoezmue** [comment] 2015-01-07 14:07
Is this a known problem on the server side? I tried implementing the Facebook Login feature again. I can signup with Facebook and also I'm able to change the username (new feature from 0.9.0). But after I login using Facebook I get the error, that this user is not permitted to access different features - for example logout. I think all API calls get rejected. 

This provides me the right user:
![image](https://cloud.githubusercontent.com/assets/7945699/5646587/4fe16eb0-967e-11e4-86eb-9a43f9e70360.png)

This is the user object which gets generated after first call of above code (I blacked out the private data)
![image](https://cloud.githubusercontent.com/assets/7945699/5646609/91679e5e-967e-11e4-908b-5fd22acebe45.png)

Here is the exception:
   class com.baasbox.android.BaasClientException :{"result":"error","message":"User XXXXXX is not authorized to access","resource":"/logout","method":"POST","request_header":{"X-BAASBOX-APPCODE":["XXXXXX"],"Connection":["Keep-Alive"],"Content-Length":["0"],"X-BB-SESSION":["XXXXXXXXX"],"Content-Type":["application/x-www-form-urlencoded"],"Accept-Encoding":["gzip"],"User-Agent":["BaasBox AndroidSDK/0.8.3"],"Host":["XXXXXX"]},"API_version":"0.9.0","http_code":401}
            at com.baasbox.android.NetworkTask.onClientError(NetworkTask.java:99)
            at com.baasbox.android.BaasUser$LogoutRequest.onClientError(BaasUser.java:1180)
            at com.baasbox.android.BaasUser$LogoutRequest.onClientError(BaasUser.java:1155)
            at com.baasbox.android.NetworkTask.parseResponse(NetworkTask.java:64)
            at com.baasbox.android.NetworkTask.asyncCall(NetworkTask.java:152)
            at com.baasbox.android.impl.Task.execute(Task.java:189)
            at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:170)

**Comment by erayoezmue** [comment] 2015-01-07 14:23
I had this problem already (https://github.com/baasbox/iOS-SDK/issues/13), which should be fixed with (https://github.com/baasbox/baasbox/issues/504)

Hope it's not my fault. :)

**Comment by giastfader** [comment] 2015-01-07 17:52
After you have changed the username, the token become invalid. Have you tried to perform a new login? Obviously using the same Facebook access token

**Comment by erayoezmue** [comment] 2015-01-07 17:59
In the Android example I don't have the change username function implemented yet. The username was changed once in the iOS version. In Android I only tried to login with Facebook (same token). My first idea was that the user owns a wrong role, but it is "registered". Should I try the login with a new FB account and without changing the username?

**Comment by erayoezmue** [comment] 2015-01-07 18:03
Okay tried it without renaming the user. This works like a charm. Maybe there is an issue with the renaming of the user? I'm not into the backend architecture so I only can guess. 

I will try to rename this user and see what exception we get.

**Comment by giastfader** [comment] 2015-01-07 18:08
When you change the user's username, all their session tokens become invalid.
But if I understand in your case the FB login API fails too.
Is it correct?

**Comment by erayoezmue** [comment] 2015-01-07 18:13
The Facebook login API works like a charm as long as I don't use the renaming feature. Now I renamed the user and now always get the exception that this user is not allowed to do anything. 

    class com.baasbox.android.BaasClientException :{"result":"error","message":"User erayozzzz is not authorized to access","resource":"/logout","method":"POST","request_header":{"X-BAASBOX-APPCODE":["XXX"],"Connection":["Keep-Alive"],"Content-Length":["0"],"X-BB-SESSION":["XXXX"],"Content-Type":["application/x-www-form-urlencoded"],"Accept-Encoding":["gzip"],"User-Agent":["BaasBox AndroidSDK/0.8.3"],"Host":["XXX"]},"API_version":"0.9.0","http_code":401}

Before I renamed the user it worked. Then I renamed it and logged out and logged in again. Now everytime I login with this user, it is not allowed to do anything. Seems that the user loses all privileges after giving it a new name.

**Comment by giastfader** [comment] 2015-01-08 09:27
Ok, we got it! 
We were able to reproduce it.
The problem is that when a new user signs up with a social network, a fake username AND a fake password are generated by the system. The fake password depends on the fake username, changing it causes a misalignment between them.
The solution is to regenerate the fake password as soon the username changes.
We are working on it.

**Closed** 2015-01-08 18:07 UTC
Labels: bug

**Comment by dirkam** [comment] 2015-01-08 18:39
@giastfader Does this solve the initial issue as well?

**Comment by giastfader** [comment] 2015-01-09 13:19
yes, I have tried it.
