### ISSUE TITLE
Class X not found in database

### ISSUE THREAD

**Issue by emresebat** [baasbox/baasbox#753] opened 2015-04-28 20:09 UTC
Hi

I have 3 collections I migrate from parse, Order, OrderItem and OrderCustomer.

After migrate I merge these collections in Order class so I can delete OrderItem and OrderCustomer collections. I tried from baasbox admin but it failed with a cluster error. So I tried db.exec and dropped OrderCustomer.

Now baasbox works but logs this error : 
```bash
2015-04-28 20:04:08,775 - [error] - application: play-akka.actor.default-dispatcher-9  java.lang.IllegalArgumentException: Class 'OrderCustomer' not found in database
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClass(ODatabaseDocumentTx.java:493)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClass(ODatabaseDocumentTx.java:483)
	at com.baasbox.dao.NodeDao.getCount(NodeDao.java:269)
	at com.baasbox.service.storage.StatisticsService.collectionsDetails(StatisticsService.java:95)
	at com.baasbox.controllers.Admin.getCollections(Admin.java:171)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$91$$anonfun$apply$91.apply(routes_routing.scala:1426)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$91$$anonfun$apply$91.apply(routes_routing.scala:1426)
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
	at play.GlobalSettings$1.call(GlobalSettings.java:64)
	at com.baasbox.controllers.actions.filters.ExtractQueryParameters.call(ExtractQueryParameters.java:44)
	at com.baasbox.controllers.actions.filters.CheckAdminRoleFilter.call(CheckAdminRoleFilter.java:51)
	at com.baasbox.controllers.actions.filters.ConnectToDBFilter.call(ConnectToDBFilter.java:81)
	at com.baasbox.controllers.actions.filters.UserCredentialWrapFilter.call(UserCredentialWrapFilter.java:74)
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Can I fix this?

**Comment by giastfader** [comment] 2015-04-29 08:34
So you dropped manually a class that is a BaasBox collection.
BaasBox maintains also an internal catalogue with the name of the collections.
Furthermore each document belonging to a collection has another object attached to it to manage links with other documents. This means that if you manually merged the classes, maybe you will be not able to create BaasBox Links. You can have unpredictable errors.

Coming back to the error, If you only drop a class you create an inconsistency into the database.
You should follow the same steps that BaasBox does from here https://github.com/baasbox/baasbox/blob/00154b7fb05f6343ae085b071178a0daa2ea0b68/app/com/baasbox/dao/CollectionDao.java#L146  on.

However I think that this specific error can be avoided deleting the collection name from the class _bb_collection.

In general, pay attention when you use the DB.exec() function. You can create inconsistencies because you bypass all the BaasBox internal logic and you can corrupt the DB.

**Closed by giastfader** 2015-04-29 08:34 UTC

**Comment by giastfader** [comment] 2015-04-29 08:36
Within a plugin you should use 
Box.DB.dropCollection('collection_name');
to drop an entire collection.

**Comment by emresebat** [comment] 2015-04-30 13:15
Thanks for your detailed answer @giastfader 

I did what I did because I of another error :) Of course first I tried to remove these collections from the admin console. OrderItem was deleted ok, but when I clicked delete for OrderCustomer I received an error about "node #45" not found etc...

I should stop and report this other error but I had to continue so I tried drop collection, probably Box.DB.dropCollection woudl give the same error with the admin console.

I like baasbox, it's a very good option for this kind of backend. My only concern is how should I deal with db problems. My db is not that big but with 0.9.2 and 0.9.4 nightly I still cannot backup my db which has 180k records. I see OutOfMemoryExceptions. 

After I fix this I will open another issue for that error.

**Comment by emresebat** [comment] 2015-04-30 13:17
Hi again

When I try to delete vertexes I receive the following, this is exactly the same error when I tried to delete the OrderCustomer collection:

```bash
script failure com.baasbox.service.scripting.base.ScriptEvalException: ScriptError: 'com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #45:0 (cluster: null)' at: <<eval>>176:16\ <eval>:176:16 com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #45:0 (cluster: null)\ \	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:111)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$Module$L:155(<eval>:176)\ \	at jdk.nashorn.internal.scripts.Script$baasbox_core.:scopeCall(baasbox.core)\ \	at jdk.nashorn.internal.scripts.Script$baasbox_core.L:134(baasbox.core:141)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:539)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:109)\ \	at jdk.nashorn.internal.scripts.Script$kasa_db_exec.L:9(kasa.db.exec:11)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$ModuleRef$L:282$L:284(<eval>:288)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:537)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.internal.objects.NativeFunction.apply(NativeFunction.java:130)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$L:306(<eval>:323)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:537)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:185)\ \	at com.baasbox.service.scripting.js.Nashorn.emitEvent(Nashorn.java:192)\ \	at com.baasbox.service.scripting.js.Nashorn.eval(Nashorn.java:92)\ \	at com.baasbox.service.scripting.js.NashornEngine.eval(NashornEngine.java:72)\ \	at com.baasbox.service.scripting.ScriptingService.invoke(ScriptingService.java:285)\ \	at com.baasbox.controllers.ScriptInvoker.invoke(ScriptInvoker.java:77)\ \	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$128$$anonfun$apply$128.apply(routes_routing.scala:1723)\ \	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$128$$anonfun$apply$128.apply(routes_routing.scala:1723)\ \	at 
```

**Comment by giastfader** [comment] 2015-05-05 15:04
As far as the OutOfMemoryError is concerned, have you tried to increase the memory to the JVM? 

The last error is caused by (my guess) a corruption of the db or of an internal index.
This is the line that suggests me the problem:
````
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #45:0 (cluster: null)
````

The DB.exec() API is powerful but dangerous.
However to access to the internal DB you can use the OrientDB 1.7.9 tools.
After you download them, use the bin/console.sh tool and connect to the db with the following command:
```
connect plocal:/FULL_PATH_OF_THE_BAASBOX_HOME/db/baasbox admin <your_admin_password>
```
Now you have full access to the db.
The first thing I'd try is to rebuild all the indices.
````
rebuild index *
````

Please stop BaasBox when use the OrientDB console.
